#!/bin/bash

echo "=========================================="
echo "Fix MySQL Remote Access"
echo "=========================================="
echo ""
echo "Container IP ที่ MySQL server เห็น: 49.228.65.203"
echo ""
echo "ต้อง SSH เข้าไปที่ MySQL server (157.85.98.150) และรันคำสั่งต่อไปนี้:"
echo ""
echo "1. SSH เข้า server:"
echo "   ssh root@157.85.98.150"
echo ""
echo "2. เข้า MySQL:"
echo "   mysql -u root -p"
echo ""
echo "3. รันคำสั่ง SQL ต่อไปนี้:"
echo ""
echo "   -- สร้าง database (ถ้ายังไม่มี)"
echo "   CREATE DATABASE IF NOT EXISTS nuxtcommerce_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo ""
echo "   -- อนุญาตให้ root เข้าถึงจาก IP นี้"
echo "   GRANT ALL PRIVILEGES ON nuxtcommerce_db.* TO 'root'@'49.228.65.203' IDENTIFIED BY 'KtmdoLt9b\$n!' WITH GRANT OPTION;"
echo ""
echo "   -- หรืออนุญาตจาก IP ใดก็ได้ (ไม่แนะนำ แต่ใช้งานง่าย)"
echo "   GRANT ALL PRIVILEGES ON nuxtcommerce_db.* TO 'root'@'%' IDENTIFIED BY 'KtmdoLt9b\$n!' WITH GRANT OPTION;"
echo ""
echo "   -- บังคับให้ MySQL ใช้การตั้งค่าใหม่"
echo "   FLUSH PRIVILEGES;"
echo ""
echo "4. ตรวจสอบว่า bind-address ถูกตั้งค่าให้รับ connection จากภายนอก:"
echo "   grep bind-address /etc/mysql/mysql.conf.d/mysqld.cnf"
echo "   # ควรเป็น: bind-address = 0.0.0.0"
echo ""
echo "5. ตรวจสอบว่า firewall เปิด port 3306:"
echo "   ufw status | grep 3306"
echo "   # หรือ"
echo "   iptables -L -n | grep 3306"
echo ""
echo "6. Restart MySQL:"
echo "   systemctl restart mysql"
echo "   # หรือ"
echo "   service mysql restart"
echo ""
echo "=========================================="
echo "หลังจากแก้ไขแล้ว ให้ restart container:"
echo "   docker-compose restart app"
echo "=========================================="
