#!/bin/bash
# Script to fix MySQL remote access on server 157.85.98.150
# Run this on the MySQL server via SSH

echo "=== MySQL Remote Access Setup ==="
echo ""
echo "Run these commands on your MySQL server (157.85.98.150):"
echo ""
echo "1. SSH into the server:"
echo "   ssh root@157.85.98.150"
echo ""
echo "2. Connect to MySQL:"
echo "   mysql -u root -p"
echo "   (Enter password: KtmdoLt9b\$n!)"
echo ""
echo "3. Run these SQL commands:"
echo ""
echo "   CREATE DATABASE IF NOT EXISTS nuxtcommerce_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
echo "   GRANT ALL PRIVILEGES ON nuxtcommerce_db.* TO 'root'@'%' IDENTIFIED BY 'KtmdoLt9b\$n!' WITH GRANT OPTION;"
echo "   FLUSH PRIVILEGES;"
echo "   EXIT;"
echo ""
echo "4. Check MySQL bind address (should be 0.0.0.0, not 127.0.0.1):"
echo "   grep bind-address /etc/mysql/my.cnf"
echo "   # If it shows 127.0.0.1, change it to 0.0.0.0"
echo ""
echo "5. Restart MySQL:"
echo "   systemctl restart mysql"
echo "   # or"
echo "   systemctl restart mysqld"
echo ""
echo "6. Check firewall (allow port 3306):"
echo "   ufw allow 3306/tcp"
echo "   # or for iptables:"
echo "   iptables -A INPUT -p tcp --dport 3306 -j ACCEPT"
echo ""
